#配置数据库信息
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/test2?characterEncoding=UTF-8&serverTimezone=Asia/Shanghai
    username: root
    password: 123123

  thymeleaf:
    cache: false

server:
  port: 8080
#配置白名单
whiteList: /login/**,/logout/**

mybatis:
  mapper-locations: classpath:mapper/*.xml

